# Change these first
owner: M4Tdev # Your GitHub username
repo: kernos-bot-upptime # Your GitHub repository name

# Add your sites here
sites:
#   - name: Kernos Discord BOT
#     url: https://kernos-discord-bot.herokuapp.com/

status-website:
  baseUrl: /kernos-bot-upptime
  name: Kernos Discord Bot Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
